- jjb/ci-management/ci-packer.yaml
> Add builder packer job

- jenkins-config/clouds/openstack/cattle/ubuntu1604-builder-2c-1g.cfg
> Add Ubuntu 16.04 builder minion

- jenkins-config/global-vars-production.sh
- jenkins-config/global-vars-sandbox.sh
Add configuration for jenkins-cfg job to manage global-vars.
> Setup global-vars management

- jjb/ci-management/ci-packer.yaml
> Add packer verify job

- jjb/openexr/openexr.yaml
- jjb/openexr/shell/build-ilmbase.sh
- jjb/openexr/shell/build-openexr-viewers.sh
- jjb/openexr/shell/build-openexr.sh
- jjb/openexr/shell/build-pyilmbase.sh
> Add openexr build verify job

- jjb/ci-management/ci-management.yaml
> Update to JJB 2.0.10

- jenkins-config/clouds/openstack/cattle/ws2016-win-builder-4c-4g.cfg
> Add ws2016 win-builder

- jjb/openexr/openexr.yaml
- jjb/openexr/shell/build-ilmbase.sh
- jjb/openexr/shell/build-openexr-viewers.sh
- jjb/openexr/shell/build-openexr.sh
- jjb/openexr/shell/build-pyilmbase.sh
- jjb/openexr/shell/stage-release.sh
> Add staging job for OpenEXR

- jenkins-config/global-vars-production.sh
- jenkins-config/global-vars-sandbox.sh
> Remove trailing / from URLs

- jjb/openexr/openexr.yaml
> Build OpenEXR on a 4c-4g system

- packer/provision/local-builder.yaml
Issue: https://jira.linuxfoundation.org/browse/RELENG-1075
> Add OpenVDB build dependencies

- jjb/openvdb/openvdb.yaml
Issue: https://jira.linuxfoundation.org/browse/RELENG-1075
> Add openvdb verify job

- jjb/opencolorio/opencolorio.yaml
- jjb/openexr/openexr.yaml
- jjb/openvdb/openvdb.yaml
- jjb/view-templates.yaml
- jjb/views.yaml
> Add JJB Views

- jjb/openvdb/openvdb.yaml
- jjb/openvdb/shell/stage-release.sh
> Add OpenVDB staging job

- jjb/openexr/openexr.yaml
Issue: https://jira.linuxfoundation.org/browse/RELENG-1101
> Add CMake verify job for OpenEXR

- jjb/opencolorio/shell/stage-release.sh
- jjb/openexr/shell/stage-release.sh
- jjb/openvdb/shell/stage-release.sh
Issue: https://jira.linuxfoundation.org/browse/RELENG-1107
> Save commit hash of build

- jjb/openexr/shell/stage-release.sh
Issue: https://jira.linuxfoundation.org/browse/RELENG-1109
> Generate source bundles for staging job

- jjb/openvdb/openvdb.yaml
The old stage repo was cleared out.
> Update openexr stage repo

- jjb/openvdb/openvdb.yaml
Attempt to disable the building of the Python module for now...
Signed-off-by: Dan Bailey <danbailey@ilm.com>
> [OpenVDB] Disable building of the Python module

- jjb/openexr/openexr.yaml
Ensure we are refreshing our staging repos regularly.
> Trigger OpenEXR stage job daily

- jenkins-config/clouds/openstack/cattle/ubuntu1604-builder-docker-2c-2g.cfg
- jjb/ci-management/ci-packer.yaml
This is to try to fix docker not actually starting on the centos image
> Switched docker image to use ubuntu

- jjb/ci-management/ci-management.yaml
This job is needed to clear out old image builds.
> Add openstack-cron job
